### ISSUE TITLE
Ice Cream Position

### ISSUE THREAD

**Issue by cmvolden** [cmvolden/frozen-not-in-time#1]
Hey @charlie-quinn ! When your eyes have stopped bleeding/when you have a minute do you mind having a look at this to see what the heck is going on with my ice cream positioning? Why it is flowing out of the background? Thank you!!

**Comment by charlie-quinn** [comment]
Hey @cmvolden sorry for the late response!

- [x] let's add a few classes to your `<div class="grid grid-middle">` to help contain your content better:
  - [x] add `wrapper` and `gutter-2` to give it a max-width and a bit of padding
- [x] this won't effect anything currently, but for the sake of staying consistent with markbot :robot:...
  - [x] first div with `unit`: change to `unit xs-1 s-1 m-3-4 l-3-4`
  - [x] first div with `unit`: remove `gutter` (this padding is unnecessary)
  - [x] second dev with `unit`: change to `unit xs-1 s-1 m-1-4 l-1-4`
- [x] remove sizing and positioning properties from your individual ice-cream flavour classes
- [x] add a class to ALL of the ice-cream pieces (I used ingredient but you can use whatever you'd like)
  - [x] target this class in your css and add some sizing and positioning properties that will apply to all:
    - [x] height: 180px; width: 180px; bottom: 100%; left: 50%; transform: translateX(-50%);
    - ⚠️**play with these values for a minute and preview in your browser to see what they're controlling** 

👋 Let's go over the animations in class together if you still need help.

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by cmvolden** [comment]
Thanks!
